// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfnEwhpmrCNXvE-KutK1sl6Z7LVgxgOlM',
    appId: '1:618469004966:web:db330d4ceced9581740667',
    messagingSenderId: '618469004966',
    projectId: 'chatapp-eab21',
    authDomain: 'chatapp-eab21.firebaseapp.com',
    storageBucket: 'chatapp-eab21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZm2Spj29Ab5e5dRG9F_-MKcXYPuuXJcw',
    appId: '1:618469004966:android:a06078f087482dda740667',
    messagingSenderId: '618469004966',
    projectId: 'chatapp-eab21',
    storageBucket: 'chatapp-eab21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDym0jQZQHTLGLgbWwTcuDoFerR3DpfQlY',
    appId: '1:618469004966:ios:b526f41efe0c1228740667',
    messagingSenderId: '618469004966',
    projectId: 'chatapp-eab21',
    storageBucket: 'chatapp-eab21.appspot.com',
    iosBundleId: 'com.example.disneyVoting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDym0jQZQHTLGLgbWwTcuDoFerR3DpfQlY',
    appId: '1:618469004966:ios:85f58d4c7f6a41a8740667',
    messagingSenderId: '618469004966',
    projectId: 'chatapp-eab21',
    storageBucket: 'chatapp-eab21.appspot.com',
    iosBundleId: 'com.example.disneyVoting.RunnerTests',
  );
}
